import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedmenuinferiorwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedmenuinferiorwidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedmenuinferiorwidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedmenuinferiorwidget/generated/GeneratedFavoritesWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedmenuinferiorwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedmenuinferiorwidget/generated/GeneratedCartWidget.dart';

/* Component Menu inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuinferiorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 411.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 411.0,
              height: 74.0,
              child: GeneratedRectangle5Widget(),
            ),
            Positioned(
              left: 29.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 28.0,
              height: 43.0,
              child: GeneratedHomeWidget(),
            ),
            Positioned(
              left: 357.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 28.0,
              height: 43.0,
              child: GeneratedProfileWidget(),
            ),
            Positioned(
              left: 269.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 43.0,
              child: GeneratedCartWidget(),
            ),
            Positioned(
              left: 186.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 39.0,
              height: 43.0,
              child: GeneratedSearchWidget(),
            ),
            Positioned(
              left: 96.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 51.0,
              height: 43.0,
              child: GeneratedFavoritesWidget(),
            )
          ]),
    ));
  }
}
