import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedcarritowidget2/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedcarritowidget2/generated/GeneratedTituloWidget4.dart';
import 'package:flutterapp/ferreteriaapp/generatedcarritowidget2/generated/GeneratedMenuinferiorWidget2.dart';
import 'package:flutterapp/ferreteriaapp/generatedcarritowidget2/generated/GeneratedLLENARWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedcarritowidget2/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedcarritowidget2/generated/GeneratedFrame4Widget.dart';

/* Frame Carrito
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarritoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 74.0,
                child: GeneratedMenuinferiorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 75.0,
                child: GeneratedTituloWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 300.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 224.0,
                child: GeneratedLLENARWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 102.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 409.9935607910156,
                height: 1.0,
                child: GeneratedLine10Widget(),
              )
            ]),
      ),
    ));
  }
}
