import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ferreteriaapp/generatedinputwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedinputwidget/generated/GeneratedIngresatuemailWidget.dart';

/* Component Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 349.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle2Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.38108882521489973;

                final double height =
                    constraints.maxHeight * 0.4166666666666667;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.06388888318080957,
                      y: constraints.maxHeight * 0.3,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIngresatuemailWidget(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
