import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedDevolucionWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedNopagadoWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedProcesandoWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedEnviadoWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedDireccionesWidget1.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedOpcionesWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedConfiguracionWidget1.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedTituloWidget3.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedMenuinferiorWidget1.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedUsuarioWidget2.dart';
import 'package:flutterapp/ferreteriaapp/generatedperfilwidget1/generated/GeneratedRectangle7Widget.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 74.0,
                child: GeneratedMenuinferiorWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 161.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 588.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 32.029850006103516,
                child: GeneratedUsuarioWidget2(),
              ),
              Positioned(
                left: 359.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedConfiguracionWidget1(),
              ),
              Positioned(
                left: 309.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedDireccionesWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 90.0,
                child: GeneratedNopagadoWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 100.0,
                child: GeneratedOpcionesWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 90.0,
                child: GeneratedProcesandoWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 90.0,
                child: GeneratedEnviadoWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 90.0,
                child: GeneratedDevolucionWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 42.0,
                child: GeneratedTituloWidget3(),
              )
            ]),
      ),
    ));
  }
}
