import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedcuentawidget/generated/GeneratedUsuarioWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedcuentawidget/generated/GeneratedCorreoWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedcuentawidget/generated/GeneratedContraseaWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedcuentawidget/generated/GeneratedTituloWidget2.dart';
import 'package:flutterapp/ferreteriaapp/generatedcuentawidget/generated/GeneratedBotonWidget1.dart';

/* Frame Cuenta
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCuentaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 75.0,
                child: GeneratedTituloWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 72.0,
                child: GeneratedCorreoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 72.0,
                child: GeneratedContraseaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 72.0,
                child: GeneratedUsuarioWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 60.0,
                child: GeneratedBotonWidget1(),
              )
            ]),
      ),
    ));
  }
}
