import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedfavoritoswidget4/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedfavoritoswidget4/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedfavoritoswidget4/generated/GeneratedMenuinferiorWidget4.dart';
import 'package:flutterapp/ferreteriaapp/generatedfavoritoswidget4/generated/GeneratedTituloWidget5.dart';
import 'package:flutterapp/ferreteriaapp/generatedfavoritoswidget4/generated/GeneratedLine9Widget1.dart';

/* Frame Favoritos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritosWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 74.0,
                child: GeneratedMenuinferiorWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 674.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 410.010986328125,
                height: 1.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 75.0,
                child: GeneratedTituloWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 410.010986328125,
                height: 1.0,
                child: GeneratedLine9Widget1(),
              )
            ]),
      ),
    ));
  }
}
