import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedconfiguracionwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedconfiguracionwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedconfiguracionwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedconfiguracionwidget/generated/GeneratedSalirWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedconfiguracionwidget/generated/GeneratedTituloWidget.dart';

/* Frame Configuracion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfiguracionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 75.0,
                child: GeneratedSalirWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 75.0,
                child: GeneratedTituloWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 135.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 135.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 135.0,
                child: GeneratedGroup4Widget(),
              )
            ]),
      ),
    ));
  }
}
