import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedBienvenidodevueltaWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedBotonWidget2.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedIngresatusdatosWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedMaskGroupWidget15.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/ferreteriaapp/generatedloginwidget/generated/GeneratedInputWidget2.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 233, 146, 52),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 388.4982604980469,
                child: GeneratedMaskGroupWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 420.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 37.0,
                child: GeneratedBienvenidodevueltaWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 30.0,
                child: GeneratedIngresatusdatosWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 60.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 99.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 25.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 60.0,
                child: GeneratedBotonWidget2(),
              )
            ]),
      ),
    ));
  }
}
