import 'package:flutter/material.dart';
import 'package:flutterapp/ferreteriaapp/generatediniciowidget5/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatediniciowidget5/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatediniciowidget5/generated/GeneratedTituloWidget6.dart';
import 'package:flutterapp/ferreteriaapp/generatediniciowidget5/generated/GeneratedMenuinferiorWidget5.dart';
import 'package:flutterapp/ferreteriaapp/generatediniciowidget5/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/ferreteriaapp/generatediniciowidget5/generated/GeneratedGroup17Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 749.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 74.0,
                child: GeneratedMenuinferiorWidget5(),
              ),
              Positioned(
                left: -1.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 594.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 40.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 40.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 75.0,
                child: GeneratedTituloWidget6(),
              ),
              Positioned(
                left: 10.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 243.00205993652344,
                height: 2.0,
                child: GeneratedLine7Widget(),
              )
            ]),
      ),
    ));
  }
}
